services:
  backend:
    build: .
    ports:
      - 3000:3000
  redis:
    image: "redis:alpine"
  db:
    image: mysql:8.0.36
    environment:
      - MYSQL_DATABASE=leagueX
      - MYSQL_ROOT_PASSWORD=alokps
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db-vol:/var/lib/mysql
volumes:
  db-vol: 